# Site title (setting it to empty removes the header title)
title: ""

# Theme for GitHub Pages (you can change "minima" to another supported theme)
theme: moonwalk

# Author (optional)
author: Adam Donen
email: adam.donen11@gmail.com

# Exclude specific files or directories
exclude:
  - README.md
  - node_modules


